import React, { useState } from "react";
import { motion } from "framer-motion";
import { Atom, Download, Share2 } from "lucide-react";
import { Button } from "../ui/Button";
import { ElementGrid } from "../periodic-table/ElementGrid";
import { CategoryLegend } from "../periodic-table/CategoryLegend";
import { SearchAndFilters } from "../periodic-table/SearchAndFilters";
import { ElementDetails } from "../periodic-table/ElementDetails";
import { Header } from "../layout/Header";
import { Sidebar } from "../layout/Sidebar";

interface PeriodicTablePageProps {
  onNavigate: (view: string) => void;
}

interface Element {
  symbol: string;
  name: string;
  atomicNumber: number;
  atomicMass: number;
  category: string;
  period: number;
  group: number;
  electronConfiguration: string;
  description: string;
  uses: string[];
  discoveredBy: string;
  yearDiscovered: number;
}

export function PeriodicTablePage({ onNavigate }: PeriodicTablePageProps) {
  const [selectedElement, setSelectedElement] = useState<Element | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("all");
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);

  const elements: Element[] = [
    {
      symbol: "H",
      name: "Hydrogen",
      atomicNumber: 1,
      atomicMass: 1.008,
      category: "nonmetal",
      period: 1,
      group: 1,
      electronConfiguration: "1s1",
      description: "Hydrogen is the lightest and most abundant element in the universe.",
      uses: ["Fuel cells", "Ammonia production", "Hydrogenation of fats and oils"],
      discoveredBy: "Henry Cavendish",
      yearDiscovered: 1766,
    },
    {
      symbol: "He",
      name: "Helium",
      atomicNumber: 2,
      atomicMass: 4.002602,
      category: "noble-gas",
      period: 1,
      group: 18,
      electronConfiguration: "1s2",
      description: "Helium is a colorless, odorless, tasteless, non-toxic, inert gas.",
      uses: ["Balloons", "Cryogenics", "Pressurizing and purging", "Welding"],
      discoveredBy: "Pierre Janssen and Norman Lockyer",
      yearDiscovered: 1868,
    },
    {
      symbol: "Li",
      name: "Lithium",
      atomicNumber: 3,
      atomicMass: 6.94,
      category: "alkali-metal",
      period: 2,
      group: 1,
      electronConfiguration: "1s2 2s1",
      description: "Lithium is a soft, silvery-white alkali metal.",
      uses: ["Rechargeable batteries", "Mood-stabilizing drugs", "Alloys"],
      discoveredBy: "Johan August Arfvedson",
      yearDiscovered: 1817,
    },
    {
      symbol: "Be",
      name: "Beryllium",
      atomicNumber: 4,
      atomicMass: 9.0121831,
      category: "alkaline-earth-metal",
      period: 2,
      group: 2,
      electronConfiguration: "1s2 2s2",
      description: "Beryllium is a hard, grayish metal naturally found in mineral rocks.",
      uses: ["Aerospace components", "X-ray windows", "Alloys with copper"],
      discoveredBy: "Louis Nicolas Vauquelin",
      yearDiscovered: 1798,
    },
    {
      symbol: "B",
      name: "Boron",
      atomicNumber: 5,
      atomicMass: 10.81,
      category: "metalloid",
      period: 2,
      group: 13,
      electronConfiguration: "1s2 2s2 2p1",
      description: "Boron is a metalloid essential for plant growth and used in various industries.",
      uses: ["Borosilicate glass", "Detergents", "Semiconductors", "Fertilizers"],
      discoveredBy: "Joseph Louis Gay-Lussac and Louis Jacques Thénard",
      yearDiscovered: 1808,
    },
    {
      symbol: "C",
      name: "Carbon",
      atomicNumber: 6,
      atomicMass: 12.011,
      category: "nonmetal",
      period: 2,
      group: 14,
      electronConfiguration: "1s2 2s2 2p2",
      description: "Carbon is a nonmetal known for its ability to form a vast number of compounds, including organic molecules.",
      uses: ["Steel production", "Filters", "Pencils (graphite)", "Organic compounds"],
      discoveredBy: "Ancient",
      yearDiscovered: -3750, // approximate (used since prehistoric times)
    },
    {
      symbol: "N",
      name: "Nitrogen",
      atomicNumber: 7,
      atomicMass: 14.007,
      category: "nonmetal",
      period: 2,
      group: 15,
      electronConfiguration: "1s2 2s2 2p3",
      description: "Nitrogen is a colorless, odorless gas that makes up 78% of Earth's atmosphere.",
      uses: ["Ammonia production", "Fertilizers", "Cryogenics", "Preservation"],
      discoveredBy: "Daniel Rutherford",
      yearDiscovered: 1772,
    },
    {
      symbol: "O",
      name: "Oxygen",
      atomicNumber: 8,
      atomicMass: 15.999,
      category: "nonmetal",
      period: 2,
      group: 16,
      electronConfiguration: "1s2 2s2 2p4",
      description: "Oxygen is essential for respiration and is the most abundant element in the Earth's crust.",
      uses: ["Breathing", "Steel making", "Water treatment", "Rocket fuel (LOX)"],
      discoveredBy: "Carl Wilhelm Scheele",
      yearDiscovered: 1771,
    },
    {
      symbol: "F",
      name: "Fluorine",
      atomicNumber: 9,
      atomicMass: 18.998403163,
      category: "halogen",
      period: 2,
      group: 17,
      electronConfiguration: "1s2 2s2 2p5",
      description: "Fluorine is a pale yellow, highly reactive gas and the most electronegative element.",
      uses: ["Toothpaste (fluoride)", "Teflon production", "Uranium enrichment", "Refrigerants"],
      discoveredBy: "Henri Moissan",
      yearDiscovered: 1886,
    },
    {
      symbol: "Ne",
      name: "Neon",
      atomicNumber: 10,
      atomicMass: 20.1797,
      category: "noble-gas",
      period: 2,
      group: 18,
      electronConfiguration: "1s2 2s2 2p6",
      description: "Neon is a noble gas used in brightly colored advertising signs.",
      uses: ["Neon signs", "High-voltage indicators", "Vacuum tubes", "Helium-neon lasers"],
      discoveredBy: "William Ramsay and Morris Travers",
      yearDiscovered: 1898,
    },
    {
      symbol: "Na",
      name: "Sodium",
      atomicNumber: 11,
      atomicMass: 22.98976928,
      category: "alkali-metal",
      period: 3,
      group: 1,
      electronConfiguration: "1s2 2s2 2p6 3s1",
      description: "Sodium is a soft, highly reactive metal and a vital element for living organisms.",
      uses: ["Table salt (NaCl)", "Street lights", "Heat exchangers", "Chemical synthesis"],
      discoveredBy: "Humphry Davy",
      yearDiscovered: 1807,
    },
    {
      symbol: "Mg",
      name: "Magnesium",
      atomicNumber: 12,
      atomicMass: 24.305,
      category: "alkaline-earth-metal",
      period: 3,
      group: 2,
      electronConfiguration: "1s2 2s2 2p6 3s2",
      description: "Magnesium is a light, silvery-white metal essential for many biological processes.",
      uses: ["Fireworks", "Alloys", "Ladders and bicycles", "Nutritional supplements"],
      discoveredBy: "Joseph Black",
      yearDiscovered: 1755,
    },
    {
      symbol: "Al",
      name: "Aluminum",
      atomicNumber: 13,
      atomicMass: 26.9815385,
      category: "post-transition-metal",
      period: 3,
      group: 13,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p1",
      description: "Aluminum is a lightweight, corrosion-resistant metal used extensively in industry.",
      uses: ["Cans and foils", "Aircraft parts", "Construction materials", "Electrical cables"],
      discoveredBy: "Hans Christian Ørsted",
      yearDiscovered: 1825,
    },
    {
      symbol: "Si",
      name: "Silicon",
      atomicNumber: 14,
      atomicMass: 28.085,
      category: "metalloid",
      period: 3,
      group: 14,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p2",
      description: "Silicon is a hard, brittle crystalline solid used as the base for most semiconductors.",
      uses: ["Microchips", "Solar cells", "Glass", "Concrete"],
      discoveredBy: "Jöns Jacob Berzelius",
      yearDiscovered: 1824,
    },
    {
      symbol: "P",
      name: "Phosphorus",
      atomicNumber: 15,
      atomicMass: 30.973761998,
      category: "nonmetal",
      period: 3,
      group: 15,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p3",
      description: "Phosphorus is a reactive nonmetal essential for life and commonly found in fertilizers.",
      uses: ["Fertilizers", "Matches", "Pesticides", "Steel production"],
      discoveredBy: "Hennig Brand",
      yearDiscovered: 1669,
    },
    {
      symbol: "S",
      name: "Sulfur",
      atomicNumber: 16,
      atomicMass: 32.06,
      category: "nonmetal",
      period: 3,
      group: 16,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p4",
      description: "Sulfur is a yellow, brittle solid known for its use in sulfuric acid and strong odor in compounds.",
      uses: ["Fertilizers", "Gunpowder", "Rubber vulcanization", "Pharmaceuticals"],
      discoveredBy: "Ancient",
      yearDiscovered: -2000, // known since ancient times
    },
    {
      symbol: "Cl",
      name: "Chlorine",
      atomicNumber: 17,
      atomicMass: 35.45,
      category: "halogen",
      period: 3,
      group: 17,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p5",
      description: "Chlorine is a greenish-yellow gas with strong disinfectant properties.",
      uses: ["Water disinfection", "PVC production", "Bleach", "Pharmaceuticals"],
      discoveredBy: "Carl Wilhelm Scheele",
      yearDiscovered: 1774,
    },
    {
      symbol: "Ar",
      name: "Argon",
      atomicNumber: 18,
      atomicMass: 39.948,
      category: "noble-gas",
      period: 3,
      group: 18,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6",
      description: "Argon is an inert noble gas commonly used in welding and lighting.",
      uses: ["Welding shield gas", "Incandescent and fluorescent lighting", "Preserving historical documents"],
      discoveredBy: "Lord Rayleigh and William Ramsay",
      yearDiscovered: 1894,
    },
    {
      symbol: "K",
      name: "Potassium",
      atomicNumber: 19,
      atomicMass: 39.0983,
      category: "alkali-metal",
      period: 4,
      group: 1,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s1",
      description: "Potassium is a soft, reactive metal essential for plant and human cell functions.",
      uses: ["Fertilizers", "Salt substitutes", "Fireworks", "Soaps"],
      discoveredBy: "Humphry Davy",
      yearDiscovered: 1807,
    },
    {
      symbol: "Ca",
      name: "Calcium",
      atomicNumber: 20,
      atomicMass: 40.078,
      category: "alkaline-earth-metal",
      period: 4,
      group: 2,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 4s2",
      description: "Calcium is a reactive, soft metal and a vital component of bones and shells.",
      uses: ["Cement and concrete", "Metallurgy", "Dietary supplements", "Fireworks"],
      discoveredBy: "Humphry Davy",
      yearDiscovered: 1808,
    },
    {
      symbol: "Sc",
      name: "Scandium",
      atomicNumber: 21,
      atomicMass: 44.955908,
      category: "transition-metal",
      period: 4,
      group: 3,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d1 4s2",
      description: "Scandium is a soft, silvery metal often classified as a rare earth element.",
      uses: ["Aerospace components", "Sports equipment", "Lighting", "Alloys"],
      discoveredBy: "Lars Fredrik Nilson",
      yearDiscovered: 1879,
    },
    {
      symbol: "Ti",
      name: "Titanium",
      atomicNumber: 22,
      atomicMass: 47.867,
      category: "transition-metal",
      period: 4,
      group: 4,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d2 4s2",
      description: "Titanium is a strong, lightweight metal known for its corrosion resistance.",
      uses: ["Aircraft", "Medical implants", "Paint pigments", "Sports equipment"],
      discoveredBy: "William Gregor",
      yearDiscovered: 1791,
    },
    {
      symbol: "V",
      name: "Vanadium",
      atomicNumber: 23,
      atomicMass: 50.9415,
      category: "transition-metal",
      period: 4,
      group: 5,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d3 4s2",
      description: "Vanadium is a ductile metal used mainly to strengthen steel alloys.",
      uses: ["Tool steels", "Catalysts", "Batteries", "Ceramics"],
      discoveredBy: "Andrés Manuel del Río",
      yearDiscovered: 1801,
    },
    {
      symbol: "Cr",
      name: "Chromium",
      atomicNumber: 24,
      atomicMass: 51.9961,
      category: "transition-metal",
      period: 4,
      group: 6,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d5 4s1",
      description: "Chromium is a hard, brittle metal known for its high polish and corrosion resistance.",
      uses: ["Stainless steel", "Plating", "Pigments", "Leather tanning"],
      discoveredBy: "Louis Nicolas Vauquelin",
      yearDiscovered: 1797,
    },
    {
      symbol: "Mn",
      name: "Manganese",
      atomicNumber: 25,
      atomicMass: 54.938044,
      category: "transition-metal",
      period: 4,
      group: 7,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d5 4s2",
      description: "Manganese is a gray-white metal used in steel production and various chemical reactions.",
      uses: ["Steel production", "Batteries", "Fertilizers", "Ceramics"],
      discoveredBy: "Johan Gottlieb Gahn",
      yearDiscovered: 1774,
    },
    {
      symbol: "Fe",
      name: "Iron",
      atomicNumber: 26,
      atomicMass: 55.845,
      category: "transition-metal",
      period: 4,
      group: 8,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d6 4s2",
      description: "Iron is a metal widely used in construction and manufacturing due to its strength and abundance.",
      uses: ["Construction", "Machinery", "Tools", "Steel production"],
      discoveredBy: "Ancient",
      yearDiscovered: -3000, // known since ancient times
    },
    {
      symbol: "Co",
      name: "Cobalt",
      atomicNumber: 27,
      atomicMass: 58.933194,
      category: "transition-metal",
      period: 4,
      group: 9,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d7 4s2",
      description: "Cobalt is a hard, lustrous metal used in alloys and batteries.",
      uses: ["Batteries", "Alloys", "Catalysts", "Magnets"],
      discoveredBy: "Georg Brandt",
      yearDiscovered: 1735,
    },
    {
      symbol: "Ni",
      name: "Nickel",
      atomicNumber: 28,
      atomicMass: 58.6934,
      category: "transition-metal",
      period: 4,
      group: 10,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d8 4s2",
      description: "Nickel is a silvery-white metal used in stainless steel and coinage.",
      uses: ["Stainless steel", "Coins", "Batteries", "Plating"],
      discoveredBy: "Axel Fredrik Cronstedt",
      yearDiscovered: 1751,
    },
    {
      symbol: "Cu",
      name: "Copper",
      atomicNumber: 29,
      atomicMass: 63.546,
      category: "transition-metal",
      period: 4,
      group: 11,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s1",
      description: "Copper is a reddish metal known for excellent electrical and thermal conductivity.",
      uses: ["Electrical wiring", "Plumbing", "Coins", "Alloys (bronze, brass)"],
      discoveredBy: "Ancient",
      yearDiscovered: -9000, // known since ancient times
    },
    {
      symbol: "Zn",
      name: "Zinc",
      atomicNumber: 30,
      atomicMass: 65.38,
      category: "transition-metal",
      period: 4,
      group: 12,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2",
      description: "Zinc is a bluish-white metal used mainly for galvanizing steel to prevent rust.",
      uses: ["Galvanizing", "Alloys (brass)", "Batteries", "Dietary supplements"],
      discoveredBy: "Andreas Marggraf",
      yearDiscovered: 1746,
    },
    {
      symbol: "Ga",
      name: "Gallium",
      atomicNumber: 31,
      atomicMass: 69.723,
      category: "post-transition-metal",
      period: 4,
      group: 13,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p1",
      description: "Gallium is a soft metal that melts just above room temperature and is used in electronics.",
      uses: ["Semiconductors", "LEDs", "Thermometers", "Solar panels"],
      discoveredBy: "Paul Emile Lecoq de Boisbaudran",
      yearDiscovered: 1875,
    },
    {
      symbol: "Ge",
      name: "Germanium",
      atomicNumber: 32,
      atomicMass: 72.63,
      category: "metalloid",
      period: 4,
      group: 14,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p2",
      description: "Germanium is a lustrous, grayish-white metalloid used in semiconductors.",
      uses: ["Fiber optics", "Infrared optics", "Transistors", "Solar cells"],
      discoveredBy: "Clemens Winkler",
      yearDiscovered: 1886,
    },
    {
      symbol: "As",
      name: "Arsenic",
      atomicNumber: 33,
      atomicMass: 74.921595,
      category: "metalloid",
      period: 4,
      group: 15,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p3",
      description: "Arsenic is a toxic metalloid used historically as a poison and in alloys.",
      uses: ["Wood preservatives", "Alloys", "Semiconductors", "Pesticides"],
      discoveredBy: "Ancient",
      yearDiscovered: -1250, // known since ancient times
    },
    {
      symbol: "Se",
      name: "Selenium",
      atomicNumber: 34,
      atomicMass: 78.971,
      category: "nonmetal",
      period: 4,
      group: 16,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p4",
      description: "Selenium is a nonmetal with properties similar to sulfur, used in electronics and glassmaking.",
      uses: ["Glass manufacturing", "Photocells", "Pigments", "Nutritional supplements"],
      discoveredBy: "Jöns Jakob Berzelius",
      yearDiscovered: 1817,
    },
    {
      symbol: "Br",
      name: "Bromine",
      atomicNumber: 35,
      atomicMass: 79.904,
      category: "halogen",
      period: 4,
      group: 17,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p5",
      description: "Bromine is a reddish-brown volatile liquid with strong odor, used in flame retardants.",
      uses: ["Flame retardants", "Pesticides", "Water treatment", "Photography chemicals"],
      discoveredBy: "Antoine Balard",
      yearDiscovered: 1826,
    },
    {
      symbol: "Kr",
      name: "Krypton",
      atomicNumber: 36,
      atomicMass: 83.798,
      category: "noble-gas",
      period: 4,
      group: 18,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6",
      description: "Krypton is a colorless, odorless noble gas used in lighting and photography.",
      uses: ["Lighting (flashlights, lasers)", "Photography", "Insulating windows"],
      discoveredBy: "Sir William Ramsay and Morris Travers",
      yearDiscovered: 1898,
    },
    {
      symbol: "Rb",
      name: "Rubidium",
      atomicNumber: 37,
      atomicMass: 85.4678,
      category: "alkali-metal",
      period: 5,
      group: 1,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 5s1",
      description: "Rubidium is a soft, silvery-white metal that reacts vigorously with water.",
      uses: ["Research", "Specialty glasses", "Atomic clocks"],
      discoveredBy: "Robert Bunsen and Gustav Kirchhoff",
      yearDiscovered: 1861,
    },
    {
      symbol: "Sr",
      name: "Strontium",
      atomicNumber: 38,
      atomicMass: 87.62,
      category: "alkaline-earth-metal",
      period: 5,
      group: 2,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 5s2",
      description: "Strontium is a soft, silver-white metal used to produce red colors in fireworks.",
      uses: ["Fireworks", "Flares", "Ceramics", "Magnets"],
      discoveredBy: "Adair Crawford",
      yearDiscovered: 1790,
    },
    {
      symbol: "Y",
      name: "Yttrium",
      atomicNumber: 39,
      atomicMass: 88.90584,
      category: "transition-metal",
      period: 5,
      group: 3,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d1 5s2",
      description: "Yttrium is a silvery-metallic element often found in rare earth minerals.",
      uses: ["LEDs", "Phosphors in TV screens", "Alloys", "Superconductors"],
      discoveredBy: "Johan Gadolin",
      yearDiscovered: 1794,
    },
    {
      symbol: "Zr",
      name: "Zirconium",
      atomicNumber: 40,
      atomicMass: 91.224,
      category: "transition-metal",
      period: 5,
      group: 4,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d2 5s2",
      description: "Zirconium is a lustrous, gray-white metal used for corrosion-resistant alloys.",
      uses: ["Nuclear reactors", "Ceramics", "Abrasives", "Jewelry"],
      discoveredBy: "Martin Heinrich Klaproth",
      yearDiscovered: 1789,
    },
    {
      symbol: "Nb",
      name: "Niobium",
      atomicNumber: 41,
      atomicMass: 92.90637,
      category: "transition-metal",
      period: 5,
      group: 5,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d4 5s1",
      description: "Niobium is a soft, gray, ductile transition metal mainly used in alloys.",
      uses: ["Superalloys", "Steel production", "Electronics", "MRI machines"],
      discoveredBy: "Charles Hatchett",
      yearDiscovered: 1801,
    },
    {
      symbol: "Mo",
      name: "Molybdenum",
      atomicNumber: 42,
      atomicMass: 95.95,
      category: "transition-metal",
      period: 5,
      group: 6,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d5 5s1",
      description: "Molybdenum is a silvery metal with a high melting point used in alloys.",
      uses: ["Steel alloys", "Electronics", "Catalysts", "Lubricants"],
      discoveredBy: "Carl Wilhelm Scheele",
      yearDiscovered: 1778,
    },
    {
      symbol: "Tc",
      name: "Technetium",
      atomicNumber: 43,
      atomicMass: 98,
      category: "transition-metal",
      period: 5,
      group: 7,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d5 5s2",
      description: "Technetium is a radioactive metal and the lightest element with no stable isotopes.",
      uses: ["Medical imaging", "Radiopharmaceuticals"],
      discoveredBy: "Emilio Segrè and Carlo Perrier",
      yearDiscovered: 1937,
    },
    {
      symbol: "Ru",
      name: "Ruthenium",
      atomicNumber: 44,
      atomicMass: 101.07,
      category: "transition-metal",
      period: 5,
      group: 8,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d7 5s1",
      description: "Ruthenium is a rare transition metal used as a catalyst and in electronics.",
      uses: ["Catalysts", "Electrical contacts", "Alloys", "Electronics"],
      discoveredBy: "Karl Ernst Claus",
      yearDiscovered: 1844,
    },
    {
      symbol: "Rh",
      name: "Rhodium",
      atomicNumber: 45,
      atomicMass: 102.9055,
      category: "transition-metal",
      period: 5,
      group: 9,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d8 5s1",
      description: "Rhodium is a rare, silvery-white metal highly resistant to corrosion.",
      uses: ["Catalytic converters", "Jewelry plating", "Electrical contacts"],
      discoveredBy: "William Hyde Wollaston",
      yearDiscovered: 1803,
    },
    {
      symbol: "Pd",
      name: "Palladium",
      atomicNumber: 46,
      atomicMass: 106.42,
      category: "transition-metal",
      period: 5,
      group: 10,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s0",
      description: "Palladium is a rare, silvery-white metal used mainly in catalytic converters.",
      uses: ["Catalytic converters", "Electronics", "Jewelry", "Hydrogen storage"],
      discoveredBy: "William Hyde Wollaston",
      yearDiscovered: 1803,
    },
    {
      symbol: "Ag",
      name: "Silver",
      atomicNumber: 47,
      atomicMass: 107.8682,
      category: "transition-metal",
      period: 5,
      group: 11,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s1",
      description: "Silver is a soft, white, lustrous metal known for the highest electrical conductivity.",
      uses: ["Jewelry", "Electronics", "Photography", "Coins"],
      discoveredBy: "Ancient",
      yearDiscovered: -5000, // known since ancient times
    },
    {
      symbol: "Cd",
      name: "Cadmium",
      atomicNumber: 48,
      atomicMass: 112.414,
      category: "transition-metal",
      period: 5,
      group: 12,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2",
      description: "Cadmium is a soft, bluish-white metal used mainly in batteries and coatings.",
      uses: ["Rechargeable batteries", "Pigments", "Coatings", "Nuclear reactors"],
      discoveredBy: "Karl Samuel Leberecht Hermann and Friedrich Stromeyer",
      yearDiscovered: 1817,
    },
    {
      symbol: "In",
      name: "Indium",
      atomicNumber: 49,
      atomicMass: 114.818,
      category: "post-transition-metal",
      period: 5,
      group: 13,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p1",
      description: "Indium is a soft, malleable metal with a low melting point, used in electronics.",
      uses: ["Touchscreens", "Semiconductors", "Alloys", "Solder"],
      discoveredBy: "Ferdinand Reich and Hieronymous Theodor Richter",
      yearDiscovered: 1863,
    },
    {
      symbol: "Sn",
      name: "Tin",
      atomicNumber: 50,
      atomicMass: 118.71,
      category: "post-transition-metal",
      period: 5,
      group: 14,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p2",
      description: "Tin is a silvery metal known for its corrosion resistance and use in alloys like bronze.",
      uses: ["Solder", "Coatings", "Alloys (bronze)", "Tin cans"],
      discoveredBy: "Ancient",
      yearDiscovered: -3500, // known since ancient times
    },
    {
      symbol: "Sb",
      name: "Antimony",
      atomicNumber: 51,
      atomicMass: 121.76,
      category: "metalloid",
      period: 5,
      group: 15,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p3",
      description: "Antimony is a brittle metalloid used in alloys and flame retardants.",
      uses: ["Flame retardants", "Alloys", "Semiconductors", "Batteries"],
      discoveredBy: "Ancient",
      yearDiscovered: -3000, // known since ancient times
    },
    {
      symbol: "Te",
      name: "Tellurium",
      atomicNumber: 52,
      atomicMass: 127.6,
      category: "metalloid",
      period: 5,
      group: 16,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p4",
      description: "Tellurium is a rare metalloid with properties between metals and nonmetals.",
      uses: ["Alloys", "Solar cells", "Thermoelectric devices", "Semiconductors"],
      discoveredBy: "Franz-Joseph Müller von Reichenstein",
      yearDiscovered: 1782,
    },
    {
      symbol: "I",
      name: "Iodine",
      atomicNumber: 53,
      atomicMass: 126.90447,
      category: "halogen",
      period: 5,
      group: 17,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p5",
      description: "Iodine is a purple-black nonmetallic solid used in medicine and photography.",
      uses: ["Antiseptics", "Photography", "Nutrition supplements", "Catalysts"],
      discoveredBy: "Bernard Courtois",
      yearDiscovered: 1811,
    },
    {
      symbol: "Xe",
      name: "Xenon",
      atomicNumber: 54,
      atomicMass: 131.293,
      category: "noble-gas",
      period: 5,
      group: 18,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6",
      description: "Xenon is a colorless, dense noble gas used in lighting and anesthesia.",
      uses: ["Lighting", "Anesthesia", "Imaging", "Ion propulsion"],
      discoveredBy: "Sir William Ramsay and Morris Travers",
      yearDiscovered: 1898,
    },
    {
      symbol: "Cs",
      name: "Cesium",
      atomicNumber: 55,
      atomicMass: 132.90545196,
      category: "alkali-metal",
      period: 6,
      group: 1,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 6s1",
      description: "Cesium is a soft, gold-colored alkali metal highly reactive and used in atomic clocks.",
      uses: ["Atomic clocks", "Photoelectric cells", "Oil drilling", "Vacuum tubes"],
      discoveredBy: "Robert Bunsen and Gustav Kirchhoff",
      yearDiscovered: 1860,
    },
    {
      symbol: "Ba",
      name: "Barium",
      atomicNumber: 56,
      atomicMass: 137.327,
      category: "alkaline-earth-metal",
      period: 6,
      group: 2,
      electronConfiguration: "1s2 2s2 2p6 3s2 3p6 3d10 4s2 4p6 4d10 5s2 5p6 6s2",
      description: "Barium is a soft, silvery alkaline earth metal used mainly in drilling fluids.",
      uses: ["Drilling fluids", "X-ray contrast agents", "Glass manufacturing", "Fireworks"],
      discoveredBy: "Carl Wilhelm Scheele",
      yearDiscovered: 1772,
    },
    {
      symbol: "La",
      name: "Lanthanum",
      atomicNumber: 57,
      atomicMass: 138.90547,
      category: "Lanthanide",
      period: 6,
      group: null,
      electronConfiguration: "[Xe] 5d1 6s2",
      description: "Lanthanum is a soft, malleable rare earth metal used in catalysts and lighting.",
      uses: ["Catalysts", "Camera lenses", "Lighting", "Battery electrodes"],
      discoveredBy: "Carl Gustaf Mosander",
      yearDiscovered: 1839,
    },
    {
      symbol: "Ce",
      name: "Cerium",
      atomicNumber: 58,
      atomicMass: 140.116,
      category: "Lanthanide",
      period: 6,
      group: null,
      electronConfiguration: "[Xe] 4f1 5d1 6s2",
      description: "Cerium is a soft, silvery metal used widely in catalytic converters and glass polishing.",
      uses: ["Catalytic converters", "Glass polishing", "Alloys", "Phosphors"],
      discoveredBy: "Martin Heinrich Klaproth, Jöns Jakob Berzelius, Wilhelm Hisinger",
      yearDiscovered: 1803,
    },
    {
      symbol: "Pr",
      name: "Praseodymium",
      atomicNumber: 59,
      atomicMass: 140.90766,
      category: "Lanthanide",
      period: 6,
      group: null,
      electronConfiguration: "[Xe] 4f3 6s2",
      description: "Praseodymium is a soft, silvery metal used in magnets and aircraft engines.",
      uses: ["Magnets", "Aircraft engines", "Glass coloring", "Lighting"],
      discoveredBy: "Carl Auer von Welsbach",
      yearDiscovered: 1885,
    },
    {
      symbol: "Nd",
      name: "Neodymium",
      atomicNumber: 60,
      atomicMass: 144.242,
      category: "Lanthanide",
      period: 6,
      group: null,
      electronConfiguration: "[Xe] 4f4 6s2",
      description: "Neodymium is a rare earth metal used in powerful magnets and lasers.",
      uses: ["Magnets", "Lasers", "Glass coloring", "Headphones"],
      discoveredBy: "Carl Auer von Welsbach",
      yearDiscovered: 1885,
    },
    {
      symbol: "Pm",
      name: "Promethium",
      atomicNumber: 61,
      atomicMass: 145,
      category: "Lanthanide",
      period: 6,
      group: null,
      electronConfiguration: "[Xe] 4f5 6s2",
      description: "Promethium is a radioactive rare earth metal with no stable isotopes, used mainly in research.",
      uses: ["Nuclear batteries", "Research"],
      discoveredBy: "Chien Shiung Wu and Emilio Segrè",
      yearDiscovered: 1945,
    },
    {
      symbol: "Sm",
      name: "Samarium",
      atomicNumber: 62,
      atomicMass: 150.36,
      category: "Lanthanide",
      period: 6,
      group: null,
      electronConfiguration: "[Xe] 4f6 6s2",
      description: "Samarium is a rare earth metal used in magnets and nuclear reactors.",
      uses: ["Magnets", "Nuclear reactors", "Lasers", "Catalysts"],
      discoveredBy: "Lecoq de Boisbaudran",
      yearDiscovered: 1879,
    },
    {
      symbol: "Eu",
      name: "Europium",
      atomicNumber: 63,
      atomicMass: 151.964,
      category: "Lanthanide",
      period: 6,
      group: null,
      electronConfiguration: "[Xe] 4f7 6s2",
      description: "Europium is a soft, silvery metal used in phosphorescent and fluorescent applications.",
      uses: ["TV screens", "Fluorescent lamps", "Euro banknotes", "Lasers"],
      discoveredBy: "Eugène-Anatole Demarçay",
      yearDiscovered: 1896,
    },
    {
      symbol: "Gd",
      name: "Gadolinium",
      atomicNumber: 64,
      atomicMass: 157.25,
      category: "Lanthanide",
      period: 6,
      group: null,
      electronConfiguration: "[Xe] 4f7 5d1 6s2",
      description: "Gadolinium is a rare earth metal used in MRI contrast agents and magnets.",
      uses: ["MRI contrast agents", "Magnets", "Nuclear reactors", "Phosphors"],
      discoveredBy: "Jean Charles Galissard de Marignac",
      yearDiscovered: 1880,
    },
    {
      symbol: "Tb",
      name: "Terbium",
      atomicNumber: 65,
      atomicMass: 158.92535,
      category: "Lanthanide",
      period: 6,
      group: null,
      electronConfiguration: "[Xe] 4f9 6s2",
      description: "Terbium is a silvery rare earth metal used in solid-state devices and phosphors.",
      uses: ["Phosphors", "Solid-state devices", "Magnets", "Lasers"],
      discoveredBy: "Carl Gustaf Mosander",
      yearDiscovered: 1843,
    },
    {
      symbol: "Dy",
      name: "Dysprosium",
      atomicNumber: 66,
      atomicMass: 162.5,
      category: "Lanthanide",
      period: 6,
      group: null,
      electronConfiguration: "[Xe] 4f10 6s2",
      description: "Dysprosium is a rare earth metal known for its high magnetic susceptibility and use in lasers.",
      uses: ["Magnets", "Lasers", "Nuclear reactors", "Data storage"],
      discoveredBy: "Paul Émile Lecoq de Boisbaudran",
      yearDiscovered: 1886,
    },
    {
      symbol: "Ho",
      name: "Holmium",
      atomicNumber: 67,
      atomicMass: 164.93033,
      category: "Lanthanide",
      period: 6,
      group: null,
      electronConfiguration: "[Xe] 4f11 6s2",
      description: "Holmium is a rare earth metal used in nuclear reactors and magnetic applications.",
      uses: ["Magnets", "Nuclear reactors", "Lasers", "Glass coloring"],
      discoveredBy: "Marc Delafontaine and Jacques-Louis Soret",
      yearDiscovered: 1878,
    },
    {
      symbol: "Er",
      name: "Erbium",
      atomicNumber: 68,
      atomicMass: 167.259,
      category: "Lanthanide",
      period: 6,
      group: null,
      electronConfiguration: "[Xe] 4f12 6s2",
      description: "Erbium is a rare earth metal used in fiber optic technology and nuclear reactors.",
      uses: ["Fiber optics", "Lasers", "Nuclear technology", "Glass coloring"],
      discoveredBy: "Carl Gustaf Mosander",
      yearDiscovered: 1843,
    },
    {
      symbol: "Tm",
      name: "Thulium",
      atomicNumber: 69,
      atomicMass: 168.93422,
      category: "Lanthanide",
      period: 6,
      group: null,
      electronConfiguration: "[Xe] 4f13 6s2",
      description: "Thulium is the least abundant lanthanide used in portable X-ray devices and lasers.",
      uses: ["Portable X-ray devices", "Lasers", "Nuclear reactors"],
      discoveredBy: "Per Teodor Cleve",
      yearDiscovered: 1879,
    },
    {
      symbol: "Yb",
      name: "Ytterbium",
      atomicNumber: 70,
      atomicMass: 173.045,
      category: "Lanthanide",
      period: 6,
      group: null,
      electronConfiguration: "[Xe] 4f14 6s2",
      description: "Ytterbium is a soft, malleable rare earth metal used in lasers and atomic clocks.",
      uses: ["Lasers", "Atomic clocks", "Electronics", "Alloys"],
      discoveredBy: "Jean Charles Galissard de Marignac",
      yearDiscovered: 1878,
    },
    {
      symbol: "Lu",
      name: "Lutetium",
      atomicNumber: 71,
      atomicMass: 174.9668,
      category: "Lanthanide",
      period: 6,
      group: null,
      electronConfiguration: "[Xe] 4f14 5d1 6s2",
      description: "Lutetium is a dense, silvery-white rare earth metal and the last element in the lanthanide series.",
      uses: ["Petroleum refining catalysts", "Medical imaging", "Research"],
      discoveredBy: "Georges Urbain",
      yearDiscovered: 1907,
    },
    {
      symbol: "Hf",
      name: "Hafnium",
      atomicNumber: 72,
      atomicMass: 178.49,
      category: "transition-metal",
      period: 6,
      group: 4,
      electronConfiguration: "[Xe] 4f14 5d2 6s2",
      description: "Hafnium is a lustrous, corrosion-resistant metal used in nuclear reactors.",
      uses: ["Nuclear control rods", "Alloys", "Semiconductors"],
      discoveredBy: "Dirk Coster and George de Hevesy",
      yearDiscovered: 1923,
    },
    {
      symbol: "Ta",
      name: "Tantalum",
      atomicNumber: 73,
      atomicMass: 180.94788,
      category: "transition-metal",
      period: 6,
      group: 5,
      electronConfiguration: "[Xe] 4f14 5d3 6s2",
      description: "Tantalum is a hard, blue-gray metal highly resistant to corrosion.",
      uses: ["Electronics (capacitors)", "Surgical implants", "Alloys"],
      discoveredBy: "Anders Ekeberg",
      yearDiscovered: 1802,
    },
    {
      symbol: "W",
      name: "Tungsten",
      atomicNumber: 74,
      atomicMass: 183.84,
      category: "transition-metal",
      period: 6,
      group: 6,
      electronConfiguration: "[Xe] 4f14 5d4 6s2",
      description: "Tungsten is a dense metal with the highest melting point of all elements.",
      uses: ["Light bulb filaments", "Cutting tools", "Alloys", "Electronics"],
      discoveredBy: "José and Fausto Elhuyar",
      yearDiscovered: 1783,
    },
    {
      symbol: "Re",
      name: "Rhenium",
      atomicNumber: 75,
      atomicMass: 186.207,
      category: "transition-metal",
      period: 6,
      group: 7,
      electronConfiguration: "[Xe] 4f14 5d5 6s2",
      description: "Rhenium is a rare, silvery-white metal with one of the highest melting points.",
      uses: ["Jet engines", "Catalysts", "Thermocouples"],
      discoveredBy: "Walter Noddack, Ida Noddack, Otto Berg",
      yearDiscovered: 1925,
    },
    {
      symbol: "Os",
      name: "Osmium",
      atomicNumber: 76,
      atomicMass: 190.23,
      category: "transition-metal",
      period: 6,
      group: 8,
      electronConfiguration: "[Xe] 4f14 5d6 6s2",
      description: "Osmium is a dense, bluish-white metal known for its hardness and high melting point.",
      uses: ["Fountain pen nibs", "Electrical contacts", "Alloys"],
      discoveredBy: "Smithson Tennant",
      yearDiscovered: 1803,
    },
    {
      symbol: "Ir",
      name: "Iridium",
      atomicNumber: 77,
      atomicMass: 192.217,
      category: "transition-metal",
      period: 6,
      group: 9,
      electronConfiguration: "[Xe] 4f14 5d7 6s2",
      description: "Iridium is a very hard, brittle, and corrosion-resistant metal.",
      uses: ["Spark plugs", "Electrical contacts", "Crucibles"],
      discoveredBy: "Smithson Tennant",
      yearDiscovered: 1803,
    },
    {
      symbol: "Pt",
      name: "Platinum",
      atomicNumber: 78,
      atomicMass: 195.084,
      category: "transition-metal",
      period: 6,
      group: 10,
      electronConfiguration: "[Xe] 4f14 5d9 6s1",
      description: "Platinum is a dense, malleable precious metal used extensively in jewelry and catalysis.",
      uses: ["Jewelry", "Catalysts", "Electronics", "Laboratory equipment"],
      discoveredBy: "Known since ancient times, formally recognized in 1735",
      yearDiscovered: 1735,
    },
    {
      symbol: "Au",
      name: "Gold",
      atomicNumber: 79,
      atomicMass: 196.966569,
      category: "transition-metal",
      period: 6,
      group: 11,
      electronConfiguration: "[Xe] 4f14 5d10 6s1",
      description: "Gold is a soft, yellow, highly conductive metal prized for its rarity and beauty.",
      uses: ["Jewelry", "Electronics", "Currency", "Dentistry"],
      discoveredBy: "Ancient",
      yearDiscovered: -4000, // known since ancient times
    },
    {
      symbol: "Hg",
      name: "Mercury",
      atomicNumber: 80,
      atomicMass: 200.59,
      category: "transition-metal",
      period: 6,
      group: 12,
      electronConfiguration: "[Xe] 4f14 5d10 6s2",
      description: "Mercury is the only metallic element that is liquid at room temperature.",
      uses: ["Thermometers", "Barometers", "Fluorescent lamps", "Dental amalgams"],
      discoveredBy: "Ancient",
      yearDiscovered: -1500, // known since ancient times
    },
    {
      symbol: "Tl",
      name: "Thallium",
      atomicNumber: 81,
      atomicMass: 204.38,
      category: "post-transition-metal",
      period: 6,
      group: 13,
      electronConfiguration: "[Xe] 4f14 5d10 6s2 6p1",
      description: "Thallium is a soft, malleable metal that is toxic and used in electronic devices.",
      uses: ["Electronics", "Medical imaging", "Rat poison", "Infrared detectors"],
      discoveredBy: "William Crookes",
      yearDiscovered: 1861,
    },
    {
      symbol: "Pb",
      name: "Lead",
      atomicNumber: 82,
      atomicMass: 207.2,
      category: "post-transition-metal",
      period: 6,
      group: 14,
      electronConfiguration: "[Xe] 4f14 5d10 6s2 6p2",
      description: "Lead is a heavy metal known for its toxicity and use in batteries and shielding.",
      uses: ["Batteries", "Radiation shielding", "Ammunition", "Alloys"],
      discoveredBy: "Ancient",
      yearDiscovered: -3500, // known since ancient times
    },
    {
      symbol: "Bi",
      name: "Bismuth",
      atomicNumber: 83,
      atomicMass: 208.9804,
      category: "post-transition-metal",
      period: 6,
      group: 15,
      electronConfiguration: "[Xe] 4f14 5d10 6s2 6p3",
      description: "Bismuth is a brittle metal with low toxicity and used in cosmetics and pharmaceuticals.",
      uses: ["Cosmetics", "Pharmaceuticals", "Alloys", "Fire detectors"],
      discoveredBy: "Ancient",
      yearDiscovered: -1500, // known since ancient times
    },
    {
      symbol: "Po",
      name: "Polonium",
      atomicNumber: 84,
      atomicMass: 209,
      category: "metalloid",
      period: 6,
      group: 16,
      electronConfiguration: "[Xe] 4f14 5d10 6s2 6p4",
      description: "Polonium is a rare, highly radioactive metalloid discovered in uranium ores.",
      uses: ["Research", "Antistatic devices", "Nuclear batteries"],
      discoveredBy: "Marie Curie and Pierre Curie",
      yearDiscovered: 1898,
    },
    {
      symbol: "At",
      name: "Astatine",
      atomicNumber: 85,
      atomicMass: 210,
      category: "halogen",
      period: 6,
      group: 17,
      electronConfiguration: "[Xe] 4f14 5d10 6s2 6p5",
      description: "Astatine is a rare, radioactive halogen with limited applications due to its scarcity.",
      uses: ["Research", "Medical applications (experimental)"],
      discoveredBy: "Dale R. Corson, Kenneth Ross MacKenzie, Emilio Segrè",
      yearDiscovered: 1940,
    },
    {
      symbol: "Rn",
      name: "Radon",
      atomicNumber: 86,
      atomicMass: 222,
      category: "noble-gas",
      period: 6,
      group: 18,
      electronConfiguration: "[Xe] 4f14 5d10 6s2 6p6",
      description: "Radon is a radioactive, colorless, odorless noble gas formed from the decay of radium.",
      uses: ["Radiotherapy (experimental)", "Research"],
      discoveredBy: "Friedrich Ernst Dorn",
      yearDiscovered: 1900,
    },
    {
      symbol: "Fr",
      name: "Francium",
      atomicNumber: 87,
      atomicMass: 223,
      category: "alkali-metal",
      period: 7,
      group: 1,
      electronConfiguration: "[Rn] 7s1",
      description: "Francium is a highly radioactive alkali metal with very limited amounts found in nature.",
      uses: ["Research"],
      discoveredBy: "Marguerite Perey",
      yearDiscovered: 1939,
    },
    {
      symbol: "Ra",
      name: "Radium",
      atomicNumber: 88,
      atomicMass: 226,
      category: "alkaline-earth-metal",
      period: 7,
      group: 2,
      electronConfiguration: "[Rn] 7s2",
      description: "Radium is a highly radioactive metal once used in luminous paints.",
      uses: ["Radiotherapy", "Luminous paints (historical)"],
      discoveredBy: "Marie Curie and Pierre Curie",
      yearDiscovered: 1898,
    },
    {
      symbol: "Ac",
      name: "Actinium",
      atomicNumber: 89,
      atomicMass: 227,
      category: "Actinide",
      period: 7,
      group: null,
      electronConfiguration: "[Rn] 6d1 7s2",
      description: "Actinium is a radioactive actinide metal used in neutron sources and research.",
      uses: ["Neutron sources", "Research"],
      discoveredBy: "Friedrich Oskar Giesel",
      yearDiscovered: 1899,
    },
    {
      symbol: "Th",
      name: "Thorium",
      atomicNumber: 90,
      atomicMass: 232.0377,
      category: "Actinide",
      period: 7,
      group: null,
      electronConfiguration: "[Rn] 6d2 7s2",
      description: "Thorium is a radioactive actinide metal proposed for use as nuclear fuel.",
      uses: ["Nuclear fuel", "Alloys", "Gas mantles"],
      discoveredBy: "Jöns Jakob Berzelius",
      yearDiscovered: 1828,
    },
    {
      symbol: "Pa",
      name: "Protactinium",
      atomicNumber: 91,
      atomicMass: 231.03588,
      category: "Actinide",
      period: 7,
      group: null,
      electronConfiguration: "[Rn] 5f2 6d1 7s2",
      description: "Protactinium is a dense, radioactive actinide metal used mainly for research.",
      uses: ["Nuclear research"],
      discoveredBy: "Otto Hahn and Lise Meitner",
      yearDiscovered: 1917,
    },
    {
      symbol: "U",
      name: "Uranium",
      atomicNumber: 92,
      atomicMass: 238.02891,
      category: "Actinide",
      period: 7,
      group: null,
      electronConfiguration: "[Rn] 5f3 6d1 7s2",
      description: "Uranium is a heavy, radioactive metal used as a fuel in nuclear reactors and weapons.",
      uses: ["Nuclear fuel", "Military applications", "Radiometric dating"],
      discoveredBy: "Martin Heinrich Klaproth",
      yearDiscovered: 1789,
    },
    {
      symbol: "Np",
      name: "Neptunium",
      atomicNumber: 93,
      atomicMass: 237,
      category: "Actinide",
      period: 7,
      group: null,
      electronConfiguration: "[Rn] 5f4 6d1 7s2",
      description: "Neptunium is a radioactive actinide metal produced in nuclear reactors.",
      uses: ["Research", "Nuclear fuel (experimental)"],
      discoveredBy: "Edwin McMillan and Philip H. Abelson",
      yearDiscovered: 1940,
    },
    {
      symbol: "Pu",
      name: "Plutonium",
      atomicNumber: 94,
      atomicMass: 244,
      category: "Actinide",
      period: 7,
      group: null,
      electronConfiguration: "[Rn] 5f6 7s2",
      description: "Plutonium is a radioactive metal used primarily in nuclear weapons and reactors.",
      uses: ["Nuclear weapons", "Nuclear reactors", "Research"],
      discoveredBy: "Glenn T. Seaborg, Edwin McMillan, Joseph W. Kennedy, Arthur Wahl",
      yearDiscovered: 1940,
    },
    {
      symbol: "Am",
      name: "Americium",
      atomicNumber: 95,
      atomicMass: 243,
      category: "Actinide",
      period: 7,
      group: null,
      electronConfiguration: "[Rn] 5f7 7s2",
      description: "Americium is a radioactive actinide metal used in smoke detectors and industrial gauges.",
      uses: ["Smoke detectors", "Industrial gauges", "Research"],
      discoveredBy: "Glenn T. Seaborg, Ralph A. James, Leon O. Morgan",
      yearDiscovered: 1944,
    },
    {
      symbol: "Cm",
      name: "Curium",
      atomicNumber: 96,
      atomicMass: 247,
      category: "Actinide",
      period: 7,
      group: null,
      electronConfiguration: "[Rn] 5f7 6d1 7s2",
      description: "Curium is a radioactive actinide metal used mainly for scientific research.",
      uses: ["Scientific research", "Radioisotope thermoelectric generators"],
      discoveredBy: "Glenn T. Seaborg, Albert Ghiorso, James, and others",
      yearDiscovered: 1944,
    },
    {
      symbol: "Bk",
      name: "Berkelium",
      atomicNumber: 97,
      atomicMass: 247,
      category: "Actinide",
      period: 7,
      group: null,
      electronConfiguration: "[Rn] 5f9 7s2",
      description: "Berkelium is a synthetic radioactive element produced in particle accelerators.",
      uses: ["Scientific research"],
      discoveredBy: "Lawrence Berkeley National Laboratory team",
      yearDiscovered: 1949,
    },
    {
      symbol: "Cf",
      name: "Californium",
      atomicNumber: 98,
      atomicMass: 251,
      category: "Actinide",
      period: 7,
      group: null,
      electronConfiguration: "[Rn] 5f10 7s2",
      description: "Californium is a radioactive metal used as a neutron source in various applications.",
      uses: ["Neutron sources", "Nuclear reactors", "Medical treatments"],
      discoveredBy: "Lawrence Berkeley National Laboratory team",
      yearDiscovered: 1950,
    },
    {
      symbol: "Es",
      name: "Einsteinium",
      atomicNumber: 99,
      atomicMass: 252,
      category: "Actinide",
      period: 7,
      group: null,
      electronConfiguration: "[Rn] 5f11 7s2",
      description: "Einsteinium is a synthetic, radioactive element produced in nuclear explosions.",
      uses: ["Scientific research"],
      discoveredBy: "Lawrence Berkeley National Laboratory team",
      yearDiscovered: 1952,
    },
    {
      symbol: "Fm",
      name: "Fermium",
      atomicNumber: 100,
      atomicMass: 257,
      category: "Actinide",
      period: 7,
      group: null,
      electronConfiguration: "[Rn] 5f12 7s2",
      description: "Fermium is a synthetic radioactive element produced in nuclear reactions.",
      uses: ["Scientific research"],
      discoveredBy: "Lawrence Berkeley National Laboratory team",
      yearDiscovered: 1952,
    },
    {
      symbol: "Md",
      name: "Mendelevium",
      atomicNumber: 101,
      atomicMass: 258,
      category: "Actinide",
      period: 7,
      group: null,
      electronConfiguration: "[Rn] 5f13 7s2",
      description: "Mendelevium is a synthetic, radioactive element used only in scientific research.",
      uses: ["Scientific research"],
      discoveredBy: "Lawrence Berkeley National Laboratory team",
      yearDiscovered: 1955,
    },
    {
      symbol: "No",
      name: "Nobelium",
      atomicNumber: 102,
      atomicMass: 259,
      category: "Actinide",
      period: 7,
      group: null,
      electronConfiguration: "[Rn] 5f14 7s2",
      description: "Nobelium is a synthetic, radioactive element used only for research purposes.",
      uses: ["Scientific research"],
      discoveredBy: "Joint Institute for Nuclear Research and Lawrence Berkeley National Laboratory",
      yearDiscovered: 1958,
    },
    {
      symbol: "Lr",
      name: "Lawrencium",
      atomicNumber: 103,
      atomicMass: 262,
      category: "Actinide",
      period: 7,
      group: null,
      electronConfiguration: "[Rn] 5f14 7s2 7p1",
      description: "Lawrencium is a synthetic, radioactive element with very limited study.",
      uses: ["Scientific research"],
      discoveredBy: "Lawrence Berkeley National Laboratory and Joint Institute for Nuclear Research",
      yearDiscovered: 1961,
    },
    {
      symbol: "Rf",
      name: "Rutherfordium",
      atomicNumber: 104,
      atomicMass: 267,
      category: "transition-metal",
      period: 7,
      group: 4,
      electronConfiguration: "[Rn] 5f14 6d2 7s2",
      description: "Rutherfordium is a synthetic element with no stable isotopes, studied only in labs.",
      uses: ["Scientific research"],
      discoveredBy: "Joint Institute for Nuclear Research and Lawrence Berkeley National Laboratory",
      yearDiscovered: 1964,
    },
    {
      symbol: "Db",
      name: "Dubnium",
      atomicNumber: 105,
      atomicMass: 270,
      category: "transition-metal",
      period: 7,
      group: 5,
      electronConfiguration: "[Rn] 5f14 6d3 7s2",
      description: "Dubnium is a synthetic element with no stable isotopes, used only in research.",
      uses: ["Scientific research"],
      discoveredBy: "Joint Institute for Nuclear Research and Lawrence Berkeley National Laboratory",
      yearDiscovered: 1967,
    },
    {
      symbol: "Sg",
      name: "Seaborgium",
      atomicNumber: 106,
      atomicMass: 271,
      category: "transition-metal",
      period: 7,
      group: 6,
      electronConfiguration: "[Rn] 5f14 6d4 7s2",
      description: "Seaborgium is a synthetic, radioactive element studied only in research labs.",
      uses: ["Scientific research"],
      discoveredBy: "Lawrence Berkeley National Laboratory and Joint Institute for Nuclear Research",
      yearDiscovered: 1974,
    },
    {
      symbol: "Bh",
      name: "Bohrium",
      atomicNumber: 107,
      atomicMass: 270,
      category: "transition-metal",
      period: 7,
      group: 7,
      electronConfiguration: "[Rn] 5f14 6d5 7s2",
      description: "Bohrium is a synthetic, highly radioactive element produced in particle accelerators.",
      uses: ["Scientific research"],
      discoveredBy: "Gesellschaft für Schwerionenforschung (GSI), Germany",
      yearDiscovered: 1981,
    },
    {
      symbol: "Hs",
      name: "Hassium",
      atomicNumber: 108,
      atomicMass: 277,
      category: "transition-metal",
      period: 7,
      group: 8,
      electronConfiguration: "[Rn] 5f14 6d6 7s2",
      description: "Hassium is a synthetic element with very short half-life, studied in labs.",
      uses: ["Scientific research"],
      discoveredBy: "Gesellschaft für Schwerionenforschung (GSI), Germany",
      yearDiscovered: 1984,
    },
    {
      symbol: "Mt",
      name: "Meitnerium",
      atomicNumber: 109,
      atomicMass: 278,
      category: "Unknown",
      period: 7,
      group: 9,
      electronConfiguration: "[Rn] 5f14 6d7 7s2 (predicted)",
      description: "Meitnerium is a synthetic, highly radioactive element with limited study.",
      uses: ["Scientific research"],
      discoveredBy: "Gesellschaft für Schwerionenforschung (GSI), Germany",
      yearDiscovered: 1982,
    },
    {
      symbol: "Ds",
      name: "Darmstadtium",
      atomicNumber: 110,
      atomicMass: 281,
      category: "Unknown",
      period: 7,
      group: 10,
      electronConfiguration: "[Rn] 5f14 6d8 7s2 (predicted)",
      description: "Darmstadtium is a synthetic, highly unstable element with short half-life.",
      uses: ["Scientific research"],
      discoveredBy: "Gesellschaft für Schwerionenforschung (GSI), Germany",
      yearDiscovered: 1994,
    },
    {
      symbol: "Rg",
      name: "Roentgenium",
      atomicNumber: 111,
      atomicMass: 282,
      category: "Unknown",
      period: 7,
      group: 11,
      electronConfiguration: "[Rn] 5f14 6d9 7s2 (predicted)",
      description: "Roentgenium is a synthetic, highly radioactive element with limited information.",
      uses: ["Scientific research"],
      discoveredBy: "Gesellschaft für Schwerionenforschung (GSI), Germany",
      yearDiscovered: 1994,
    },
    {
      symbol: "Cn",
      name: "Copernicium",
      atomicNumber: 112,
      atomicMass: 285,
      category: "transition-metal",
      period: 7,
      group: 12,
      electronConfiguration: "[Rn] 5f14 6d10 7s2 (predicted)",
      description: "Copernicium is a synthetic, radioactive element named after astronomer Nicolaus Copernicus.",
      uses: ["Scientific research"],
      discoveredBy: "Gesellschaft für Schwerionenforschung (GSI), Germany",
      yearDiscovered: 1996,
    },
    {
      symbol: "Nh",
      name: "Nihonium",
      atomicNumber: 113,
      atomicMass: 286,
      category: "Unknown",
      period: 7,
      group: 13,
      electronConfiguration: "[Rn] 5f14 6d10 7s2 7p1 (predicted)",
      description: "Nihonium is a synthetic, radioactive element named after Japan (Nihon).",
      uses: ["Scientific research"],
      discoveredBy: "Riken, Japan",
      yearDiscovered: 2004,
    },
    {
      symbol: "Fl",
      name: "Flerovium",
      atomicNumber: 114,
      atomicMass: 289,
      category: "Unknown",
      period: 7,
      group: 14,
      electronConfiguration: "[Rn] 5f14 6d10 7s2 7p2 (predicted)",
      description: "Flerovium is a synthetic, radioactive element named after the Flerov Laboratory of Nuclear Reactions.",
      uses: ["Scientific research"],
      discoveredBy: "Joint Institute for Nuclear Research (JINR), Russia",
      yearDiscovered: 1998,
    },
    {
      symbol: "Mc",
      name: "Moscovium",
      atomicNumber: 115,
      atomicMass: 290,
      category: "Unknown",
      period: 7,
      group: 15,
      electronConfiguration: "[Rn] 5f14 6d10 7s2 7p3 (predicted)",
      description: "Moscovium is a synthetic, radioactive element named after Moscow.",
      uses: ["Scientific research"],
      discoveredBy: "Joint Institute for Nuclear Research (JINR), Russia and Lawrence Livermore National Laboratory (LLNL), USA",
      yearDiscovered: 2003,
    },
    {
      symbol: "Lv",
      name: "Livermorium",
      atomicNumber: 116,
      atomicMass: 293,
      category: "Unknown",
      period: 7,
      group: 16,
      electronConfiguration: "[Rn] 5f14 6d10 7s2 7p4 (predicted)",
      description: "Livermorium is a synthetic, highly radioactive element with limited study.",
      uses: ["Scientific research"],
      discoveredBy: "Joint Institute for Nuclear Research (JINR), Russia and Lawrence Livermore National Laboratory (LLNL), USA",
      yearDiscovered: 2000,
    },
    {
      symbol: "Ts",
      name: "Tennessine",
      atomicNumber: 117,
      atomicMass: 294,
      category: "Unknown",
      period: 7,
      group: 17,
      electronConfiguration: "[Rn] 5f14 6d10 7s2 7p5 (predicted)",
      description: "Tennessine is a synthetic, highly radioactive element named after the US state of Tennessee.",
      uses: ["Scientific research"],
      discoveredBy: "Joint Institute for Nuclear Research (JINR), Russia and Oak Ridge National Laboratory (ORNL), USA",
      yearDiscovered: 2010,
    },
    {
      symbol: "Og",
      name: "Oganesson",
      atomicNumber: 118,
      atomicMass: 294,
      category: "noble-gas",
      period: 7,
      group: 18,
      electronConfiguration: "[Rn] 5f14 6d10 7s2 7p6 (predicted)",
      description: "Oganesson is a synthetic, highly radioactive noble gas with very limited data.",
      uses: ["Scientific research"],
      discoveredBy: "Joint Institute for Nuclear Research (JINR), Russia and Lawrence Livermore National Laboratory (LLNL), USA",
      yearDiscovered: 2002,
    },
  ];

  const categories = [
    { id: "all", label: "All Elements", color: "bg-secondary" },
    { id: "alkali-metal", label: "Alkali Metals", color: "bg-danger" },
    { id: "alkaline-earth-metal", label: "Alkaline Earth", color: "bg-warning" },
    { id: "transition-metal", label: "Transition Metals", color: "bg-info" },
    { id: "post-transition-metal", label: "Post-transition", color: "bg-primary" },
    { id: "metalloid", label: "Metalloids", color: "bg-success" },
    { id: "nonmetal", label: "Nonmetals", color: "bg-dark" },
    { id: "halogen", label: "Halogens", color: "bg-primary-red" },
    { id: "noble-gas", label: "Noble Gases", color: "bg-accent-red" },
  ];

  const getCategoryColor = (category: string) => {
    const categoryData = categories.find((c) => c.id === category);
    return categoryData?.color || "bg-secondary";
  };

  const filteredElements = elements.filter((element) => {
    const matchesSearch =
      element.name.toLowerCase().includes(searchQuery.toLowerCase()) || element.symbol.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesCategory = selectedCategory === "all" || element.category === selectedCategory;
    return matchesSearch && matchesCategory;
  });

  return (
    <div className="min-vh-100 bg-light-bg d-flex">
      <Sidebar isOpen={isSidebarOpen} onClose={() => setIsSidebarOpen(false)} activeView="periodic-table" onViewChange={onNavigate} />

      <div className="flex-fill d-flex flex-column overflow-hidden">
        <Header onMenuToggle={() => setIsSidebarOpen(!isSidebarOpen)} isSidebarOpen={isSidebarOpen} onNavigate={onNavigate} />

        <main className="flex-fill overflow-auto">
          {/* Hero Section */}
          <section className="position-relative overflow-hidden bg-gradient-primary text-white py-5">
            <div className="container-lg py-5">
              <div className="text-center">
                <motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }}>
                  <div
                    className="bg-white bg-opacity-20 rounded-circle d-inline-flex align-items-center justify-content-center mb-4"
                    style={{ width: "80px", height: "80px" }}
                  >
                    <Atom className="text-white" size={40} />
                  </div>
                  <h1 className="display-3 fw-bold mb-4">Interactive Periodic Table</h1>
                  <p className="lead mb-5 mx-auto" style={{ maxWidth: "600px" }}>
                    Explore the elements that make up our universe. Click on any element to discover its properties, uses, and fascinating
                    history.
                  </p>
                  <div className="d-flex flex-column flex-sm-row gap-3 justify-content-center">
                    <Button variant="secondary" size="lg" className="bg-white text-primary-red border-white">
                      <Download size={20} className="me-2" />
                      Download Reference
                    </Button>
                    <Button variant="outline-secondary" size="lg" className="border-white text-white">
                      <Share2 size={20} className="me-2" />
                      Share Table
                    </Button>
                  </div>
                </motion.div>
              </div>
            </div>
          </section>

          {/* Search and Filters */}
          <section className="py-4 bg-white border-bottom">
            <div className="container-lg">
              <SearchAndFilters
                searchQuery={searchQuery}
                setSearchQuery={setSearchQuery}
                selectedCategory={selectedCategory}
                setSelectedCategory={setSelectedCategory}
                categories={categories}
              />
            </div>
          </section>

          {/* Category Legend */}
          <section className="py-4 bg-light-bg">
            <div className="container-lg">
              <CategoryLegend categories={categories} />
            </div>
          </section>

          {/* Periodic Table Grid */}
          <section className="py-5 bg-white">
            <div className="container-lg">
              <ElementGrid elements={filteredElements} onElementClick={setSelectedElement} getCategoryColor={getCategoryColor} />
            </div>
          </section>

          {/* Element Details Modal */}
          {selectedElement && (
            <ElementDetails element={selectedElement} onClose={() => setSelectedElement(null)} getCategoryColor={getCategoryColor} />
          )}
        </main>
      </div>
    </div>
  );
}
